################################################################################
# \file ide.mk
#
# \brief
# IDE-specific targets and variables
#
################################################################################
# \copyright
# Copyright (c) 2018-2026, Infineon Technologies AG, or an affiliate of
# Infineon Technologies AG. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Interface version 5 added feature to allow export to UVision and EmbeddedWorkbench to also export a postbuild command.
include $(MTB_TOOLS__CORE_DIR)/make/core/interface_version_4/ide.mk

_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE:=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/core_ide_prepost_build_data.txt
ewarm8 uvision5: core_ide_prepost_build_data
ewarm8 uvision5: MTB_CORE__EXPORT_CMDLINE += -build_data $(_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE)
# Output INCLUDES and DEFINES using echo so that those will have shell quoting rules.
core_ide_prepost_build_data:
	$(call mtb__file_write,$(_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE))
ifeq (,$(COMBINE_SIGN_JSON))
	$(call mtb__file_append,$(_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE),POSTBUILD=make ide_postbuild TOOLCHAIN=$(TOOLCHAIN))
else
	$(call mtb__file_append,$(_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE),POSTBUILD=export MTB_SIGN_COMBINE__SKIP_CHECK=1 && make ide_postbuild TOOLCHAIN=$(TOOLCHAIN))
endif
	$(call mtb__file_append,$(_MTB_CORE__IDE_PREPOST_BUILD_DATA_FILE),VCORE_ATTRS=$(VCORE_ATTRS))

_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE:=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/core_ide_project_structure_data.txt
ewarm8 uvision5: core_ide_project_structure_data
ewarm8 uvision5: MTB_CORE__EXPORT_CMDLINE += -dfp_data $(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE)
core_ide_project_structure_data:
	$(call mtb__file_write,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),PRJ_DIR=$(call mtb__path_normalize,.))
ifeq (PROJECT,$(MTB_TYPE))
	$(call mtb__file_append,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),APP_DIR=$(call mtb__path_normalize,..))
else
	$(call mtb__file_append,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),APP_DIR=$(call mtb__path_normalize,.))
endif
	$(call mtb__file_append,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),MTB_TYPE=$(MTB_TYPE))
ifeq (PROJECT,$(MTB_TYPE))
	$(call mtb__file_append,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),MTB_APPLICATION_SUBPROJECTS=$(MTB_APPLICATION_SUBPROJECTS))
else
	$(call mtb__file_append,$(_MTB_CORE__IDE_PROJECT_STRUCTURE_DATA_FILE),MTB_APPLICATION_SUBPROJECTS=$(_MTB_CORE__PRJ_PATH_NAME))
endif


ifeq (PROJECT,$(MTB_TYPE))
ifneq (,$(NSC_VENEER))
ewarm8 uvision5: core_ide_app_veneer_key_data
uvision5: core_uv_veneer_key_data

_MTB_CORE__IDE_APPLICATION_DATA_FILE_DIR:=../build/ideexport
_MTB_CORE__IDE_APPLICATION_DATA_FILE:=$(_MTB_CORE__IDE_APPLICATION_DATA_FILE_DIR)/core_ide_veneer_data.txt

$(_MTB_CORE__IDE_APPLICATION_DATA_FILE_DIR):
	mkdir -p $@

core_ide_app_veneer_key_data: $(_MTB_CORE__IDE_APPLICATION_DATA_FILE_DIR)

# This file is generated by the first project and then appended by each subsequent project.
ewarm8 uvision5: MTB_CORE__EXPORT_CMDLINE += -build_data $(_MTB_CORE__IDE_APPLICATION_DATA_FILE)

# Path to csolution veneer.
core_ide_app_veneer_key_data:
ifneq (,$(_MTB_CORE__IDE_IS_FIRST_CORE))
	$(call mtb__file_write,$(_MTB_CORE__IDE_APPLICATION_DATA_FILE))
endif
ifneq ($(filter SECURE,$(VCORE_ATTRS)),)
	$(call mtb__file_append,$(_MTB_CORE__IDE_APPLICATION_DATA_FILE),VENEER_KEY_S=$(_MTB_CORE__PRJ_PATH_NAME)=$(call mtb__path_normalize,$(NSC_VENEER)))
endif
ifneq ($(filter NON_SECURE,$(VCORE_ATTRS)),)
	$(call mtb__file_append,$(_MTB_CORE__IDE_APPLICATION_DATA_FILE),VENEER_KEY_NS=$(_MTB_CORE__PRJ_PATH_NAME)=$(call mtb__path_normalize,$(NSC_VENEER)))
endif

# Path to uvision cprj project veneer. UV using cprj does not allow specify path to veneer. Instead if a fixed value based on project name used.
core_uv_veneer_key_data: core_ide_app_veneer_key_data
ifneq ($(filter SECURE,$(VCORE_ATTRS)),)
	$(call mtb__file_append,$(_MTB_CORE__IDE_APPLICATION_DATA_FILE),VENEER_KEY_CPRJ=$(call mtb__path_normalize,./$(CY_IDE_PRJNAME)_Objects/$(CY_IDE_PRJNAME).axf_CMSE_Lib.o))
endif

endif #ifneq (,$(NSC_VENEER))
endif #ifeq (PROJECT,$(MTB_TYPE))

.PHONY: core_ide_prepost_build_data core_ide_project_structure_data core_ide_app_veneer_key_data core_uv_veneer_key_data